### ISSUE TITLE
Have plan for VSCode?

### ISSUE THREAD

**Issue by liuyatao** [ElemeFE/element-helper#1]

**Comment by ShowJoy** [comment]
有，目前正观察atom中使用情况，下载量超过100就开始~~^-^

**Comment by HerringtonDarkholme** [comment]
Hi, I want to migrate this plugin to https://github.com/octref/vetur. 

Vetur is the most popular extension for Vue in vscode. It is extensible enough to support Element out of box.  It is also MIT licensed. No license issue should occur.

@ElementFE What's your opinion?

**Comment by ShowJoy** [comment]
@HerringtonDarkholme 
Hi, I quite approve of your plan,  just do it!

**Comment by HerringtonDarkholme** [comment]
Pull Request is here! https://github.com/octref/vetur/pull/234

**Comment by Leopoldthecoder** [comment]
@ShowJoy 

After a discussion with @HerringtonDarkholme, I have published `element-tags.json` and `element-attributes.json` to [npm](https://www.npmjs.com/package/element-helper-json), so you can use directly instead of maintaining these two files here. Usage: https://github.com/octref/vetur/pull/234#issuecomment-309277127

**Comment by ShowJoy** [comment]
@Leopoldthecoder Great!  thanks.

**Comment by Leopoldthecoder** [comment]
No problem.👏

**Comment by ShowJoy** [comment]
@liuyatao Although a little late...., VSCode version has done! see [vscode-element-helper](https://marketplace.visualstudio.com/items?itemName=ElemeFE.vscode-element-helper)
